### ISSUE TITLE
break ember-cli

### ISSUE THREAD

**Issue by feitian124** [locks/ember-localstorage-adapter#82]
i'm useing ember-cli 0.046 and after `npm install --save-dev ember-localstorage-adapter` 
i can not use `ember g adapter application` or `ember server`, it reports:  

``` shell
23:42 $ ember s
version: 0.0.46
Cannot read property 'pkg' of null
TypeError: Cannot read property 'pkg' of null
    at Function.Addon.resolvePath (/home/ming/work/chat/node_modules/ember-cli/lib/models/addon.js:283:18)
    at Function.Addon.lookup (/home/ming/work/chat/node_modules/ember-cli/lib/models/addon.js:298:22)
    at /home/ming/work/chat/node_modules/ember-cli/lib/models/project.js:180:34
    at visit (/home/ming/work/chat/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
    at visit (/home/ming/work/chat/node_modules/ember-cli/lib/utilities/DAG.js:21:5)
    at DAG.topsort (/home/ming/work/chat/node_modules/ember-cli/lib/utilities/DAG.js:82:7)
    at Project.initializeAddons (/home/ming/work/chat/node_modules/ember-cli/lib/models/project.js:178:9)
    at Project.eachAddonCommand (/home/ming/work/chat/node_modules/ember-cli/lib/models/project.js:205:10)
    at module.exports (/home/ming/work/chat/node_modules/ember-cli/lib/cli/lookup-command.js:52:13)
    at CLI.<anonymous> (/home/ming/work/chat/node_modules/ember-cli/lib/cli/cli.js:31:26)
```

below is my ember version, 

``` shell
DEBUG: ------------------------------- vendor.js:28037
DEBUG: Ember      : 1.7.0 vendor.js:28037
DEBUG: Ember Data : 1.0.0-beta.10 vendor.js:28037
DEBUG: Handlebars : 1.3.0 vendor.js:28037
DEBUG: jQuery     : 1.11.1 vendor.js:28037
DEBUG: ------------------------------- 
```

anyone can do me a favor? thanks

**Comment by mecampbellsoup** [comment]
@kurko we've hit a very similar bug to the one listed at the beginning of this issue thread. I've been able to identify the guilty dependency (in our case it's `ember-cli-gzip`, and in particular its `ember-cli-sri` add-on which seems to be specified in an `after` hook of some sort in [`node_modules/ember-cli-gzip/package.json`](https://www.dropbox.com/s/xtm92o7q3mvxrty/Screenshot%202015-09-15%2011.15.15.png?dl=0)).

Any high-level recommendations on how to work through this issue?

**Comment by kurko** [comment]
Not really, @mecampbellsoup :( haven't experienced this issue
